definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  errcode.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  model.Article:
    properties:
      content:
        type: string
      cover_image_url:
        type: string
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      desc:
        type: string
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      state:
        type: integer
      title:
        type: string
    type: object
  model.ArticleSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Article'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
        type: object
    type: object
  model.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  model.TagSwapper:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
        type: object
    type: object
info:
  contact: {}
  description: Go microservices
  license: {}
  termsOfService: https://github.com/go-microservices
  title: blog microservice
  version: "1.0"
paths:
  /api/v1/articles:
    get:
      parameters:
      - description: articleName
        in: query
        name: name
        type: string
      - description: tagId
        in: query
        name: tag_id
        type: integer
      - description: state
        in: query
        name: state
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.ArticleSwagger'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get a list of articles
  /api/v1/articles/{id}:
    delete:
      parameters:
      - description: id for the article
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/string'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get a list of articles
    get:
      parameters:
      - description: id for the article
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.Article'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get an article
    put:
      parameters:
      - description: tag_id
        in: body
        name: tag_id
        required: true
        schema:
          type: string
      - description: title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: description for the article
        in: body
        name: desc
        schema:
          type: string
      - description: cover_image_url
        in: body
        name: cover_image_url
        required: true
        schema:
          type: string
      - description: content
        in: body
        name: content
        required: true
        schema:
          type: string
      - description: modifier
        in: body
        name: modified_by
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.ArticleSwagger'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get a list of articles
  /api/v1/tags:
    get:
      parameters:
      - description: tagName
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: status
        enum:
        - 0
        - 1
        in: query
        name: name
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.TagSwapper'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get a list of tags
    post:
      parameters:
      - description: tagName
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: status
        enum:
        - 0
        - 1
        in: query
        name: name
        type: integer
      - description: creator
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: create a tag
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: id for tag
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/string'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: delete a tag
    put:
      parameters:
      - description: id for tag
        in: path
        name: id
        required: true
        type: integer
      - description: tag name
        in: body
        maxLength: 100
        minLength: 3
        name: name
        schema:
          type: string
      - default: 1
        description: state
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: integer
      - description: modifier
        in: body
        maxLength: 100
        minLength: 3
        name: modified_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: Failure
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: update  atag
swagger: "2.0"
